version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: arogya_postgres
    environment:
      POSTGRES_DB: arogya_db
      POSTGRES_USER: arogya_user
      POSTGRES_PASSWORD: arogya_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mongodb:
    image: mongo:6
    container_name: arogya_mongodb
    environment:
      MONGO_INITDB_DATABASE: arogya_logs
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: arogya_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  mongodb_data:
  redis_data: